### ISSUE TITLE
RFID-RC522 on pi zero not working after fresh install

### ISSUE THREAD

**Issue by NicoBleh** [MiczFlor/RPi-Jukebox-RFID#1197]
### What I did

Setup a pi zero w with I2S PCM5102 DAC and RFID-RC522 and Rasperian Pi QS Lite.
Used default install script for Buster to get the Phoniebox running.

### What happened

When placing a card on the RFID reader it does not read the card.

### I expected this to happen

When placing a card on the RFID reader it reads out the card and shows it at last read card.

### Further information that might help

```
Dec 12 20:07:42 raspberrypi rsyslogd:  [origin software="rsyslogd" swVersion="8.1901.0" x-pid="278" x-info="https://www.rsyslog.com"] rsyslogd was HUPed
Dec 12 20:07:42 raspberrypi systemd[1]: phoniebox-gpio-control.service: Main process exited, code=exited, status=1/FAILURE
Dec 12 20:07:42 raspberrypi systemd[1]: phoniebox-gpio-control.service: Failed with result 'exit-code'.
Dec 12 20:07:42 raspberrypi systemd[1]: logrotate.service: Succeeded.
Dec 12 20:07:43 raspberrypi systemd[1]: Started Rotate log files.
Dec 12 20:07:44 raspberrypi systemd[1]: Started Session 3 of user pi.
Dec 12 20:07:46 raspberrypi systemd[1]: phoniebox-gpio-control.service: Service RestartSec=3s expired, scheduling restart.
Dec 12 20:07:46 raspberrypi systemd[1]: phoniebox-gpio-control.service: Scheduled restart job, restart counter is at 2.
Dec 12 20:07:46 raspberrypi systemd[1]: phpsessionclean.service: Succeeded.
Dec 12 20:07:46 raspberrypi systemd[1]: Started Clean php session files.
Dec 12 20:07:46 raspberrypi systemd[1]: Stopped Phoniebox GPIO Control Service.
Dec 12 20:07:46 raspberrypi systemd[1]: Started Phoniebox GPIO Control Service.
Dec 12 20:07:52 raspberrypi PhonieboxGPIOControl[1110]: INFO:root:['VolumeControl', 'PrevNextControl', 'PlayPause', 'Shutdown', 'Volume0', 'VolumeUp', 'VolumeDown', 'NextSong', 'PrevSong', 'Halt']
Dec 12 20:07:52 raspberrypi PhonieboxGPIOControl[1110]: INFO:root:adding GPIO-Device, VolumeControl
Dec 12 20:07:52 raspberrypi PhonieboxGPIOControl[1110]: INFO:gpio_control:VolumeControl as TwoButtonControl
Dec 12 20:07:52 raspberrypi PhonieboxGPIOControl[1110]: INFO:GPIODevices.two_button_control:adding new action
Dec 12 20:07:52 raspberrypi PhonieboxGPIOControl[1110]: INFO:GPIODevices.simple_button:{}: set when_pressed
Dec 12 20:07:52 raspberrypi PhonieboxGPIOControl[1110]: INFO:GPIODevices.simple_button:add new action
Dec 12 20:07:53 raspberrypi PhonieboxGPIOControl[1110]: INFO:GPIODevices.simple_button:{}: set when_pressed
Dec 12 20:07:53 raspberrypi PhonieboxGPIOControl[1110]: INFO:GPIODevices.simple_button:add new action
Dec 12 20:07:53 raspberrypi PhonieboxGPIOControl[1110]: INFO:root:adding GPIO-Device, PrevNextControl
Dec 12 20:07:53 raspberrypi PhonieboxGPIOControl[1110]: INFO:root:adding TwoButtonControl
Dec 12 20:07:53 raspberrypi PhonieboxGPIOControl[1110]: INFO:GPIODevices.two_button_control:adding new action
Dec 12 20:07:53 raspberrypi PhonieboxGPIOControl[1110]: INFO:GPIODevices.simple_button:{}: set when_pressed
Dec 12 20:07:53 raspberrypi PhonieboxGPIOControl[1110]: INFO:GPIODevices.simple_button:add new action
Dec 12 20:07:54 raspberrypi mpd: zeroconf: No global port, disabling zeroconf
Dec 12 20:07:54 raspberrypi systemd[1]: Started Music Player Daemon.
Dec 12 20:07:54 raspberrypi systemd[1]: Starting Phoniebox Startup...
Dec 12 20:07:54 raspberrypi systemd[1]: man-db.service: Succeeded.
Dec 12 20:07:54 raspberrypi systemd[1]: Started Daily man-db regeneration.
Dec 12 20:07:55 raspberrypi bash[1204]: AUDIOFOLDERSPATH="/home/pi/RPi-Jukebox-RFID/shared/audiofolders"
Dec 12 20:07:55 raspberrypi bash[1204]: PLAYLISTSFOLDERPATH="/home/pi/RPi-Jukebox-RFID/playlists"
Dec 12 20:07:55 raspberrypi bash[1204]: SECONDSWIPE="RESTART"
Dec 12 20:07:55 raspberrypi bash[1204]: SECONDSWIPEPAUSE="2"
Dec 12 20:07:55 raspberrypi bash[1204]: SECONDSWIPEPAUSECONTROLS="ON"
Dec 12 20:07:55 raspberrypi bash[1204]: AUDIOIFACENAME="0"
Dec 12 20:07:55 raspberrypi bash[1204]: VOLUMEMANAGER="mpd"
Dec 12 20:07:55 raspberrypi bash[1204]: AUDIOVOLCHANGESTEP="3"
Dec 12 20:07:55 raspberrypi bash[1204]: AUDIOVOLMAXLIMIT="75"
Dec 12 20:07:55 raspberrypi bash[1204]: AUDIOVOLMINLIMIT="1"
Dec 12 20:07:55 raspberrypi bash[1204]: AUDIOVOLSTARTUP="75"
Dec 12 20:07:55 raspberrypi bash[1204]: VOLCHANGEIDLE="TRUE"
Dec 12 20:07:55 raspberrypi bash[1204]: IDLETIMESHUTDOWN="0"
Dec 12 20:07:55 raspberrypi bash[1204]: POWEROFFCMD="sudo poweroff"
Dec 12 20:07:55 raspberrypi bash[1204]: SHOWCOVER="ON"
Dec 12 20:07:55 raspberrypi bash[1204]: READWLANIPYN="OFF"
Dec 12 20:07:55 raspberrypi bash[1204]: EDITION="classic"
Dec 12 20:07:55 raspberrypi bash[1204]: LANG="de-DE"
Dec 12 20:07:55 raspberrypi bash[1204]: VERSION="2.2 - 305325d - master"
Dec 12 20:07:55 raspberrypi bash[1204]: CMDVOLUP=""
Dec 12 20:07:55 raspberrypi bash[1204]: CMDVOLDOWN=""
Dec 12 20:07:55 raspberrypi bash[1204]: CMDNEXT=""
Dec 12 20:07:55 raspberrypi bash[1204]: CMDPREV=""
Dec 12 20:07:55 raspberrypi bash[1204]: CMDREWIND=""
Dec 12 20:07:55 raspberrypi bash[1204]: CMDSEEKFORW=""
Dec 12 20:07:55 raspberrypi bash[1204]: CMDSEEKBACK=""
Dec 12 20:07:55 raspberrypi bash[1204]: 75 is the mpd startup volume
Dec 12 20:07:55 raspberrypi PhonieboxGPIOControl[1110]: VolumeControl
Dec 12 20:07:55 raspberrypi PhonieboxGPIOControl[1110]: PrevNextControl
Dec 12 20:07:55 raspberrypi PhonieboxGPIOControl[1110]: Traceback (most recent call last):
Dec 12 20:07:55 raspberrypi PhonieboxGPIOControl[1110]:   File "/home/pi/RPi-Jukebox-RFID/components/gpio_control/gpio_control.py", line 104, in <module>
Dec 12 20:07:55 raspberrypi PhonieboxGPIOControl[1110]:     devices = get_all_devices(config)
Dec 12 20:07:55 raspberrypi PhonieboxGPIOControl[1110]:   File "/home/pi/RPi-Jukebox-RFID/components/gpio_control/gpio_control.py", line 82, in get_all_devices
Dec 12 20:07:55 raspberrypi PhonieboxGPIOControl[1110]:     device = generate_device(config[section], section)
Dec 12 20:07:55 raspberrypi PhonieboxGPIOControl[1110]:   File "/home/pi/RPi-Jukebox-RFID/components/gpio_control/gpio_control.py", line 45, in generate_device
Dec 12 20:07:55 raspberrypi PhonieboxGPIOControl[1110]:     name=deviceName)
Dec 12 20:07:55 raspberrypi PhonieboxGPIOControl[1110]:   File "/home/pi/RPi-Jukebox-RFID/components/gpio_control/GPIODevices/two_button_control.py", line 79, in __init__
Dec 12 20:07:55 raspberrypi PhonieboxGPIOControl[1110]:     self.btn1.when_pressed = generatedTwoButtonFunctionCall
Dec 12 20:07:55 raspberrypi PhonieboxGPIOControl[1110]:   File "/home/pi/RPi-Jukebox-RFID/components/gpio_control/GPIODevices/simple_button.py", line 100, in when_pressed
Dec 12 20:07:55 raspberrypi PhonieboxGPIOControl[1110]:     GPIO.add_event_detect(self.pin, edge=self.edge, callback=self.callbackFunctionHandler, bouncetime=self.bouncetime)
Dec 12 20:07:55 raspberrypi PhonieboxGPIOControl[1110]: RuntimeError: Failed to add edge detection
Dec 12 20:07:55 raspberrypi systemd[1]: phoniebox-gpio-control.service: Main process exited, code=exited, status=1/FAILURE
Dec 12 20:07:55 raspberrypi systemd[1]: phoniebox-gpio-control.service: Failed with result 'exit-code'.
Dec 12 20:07:58 raspberrypi bash[1204]: OK MPD 0.21.4
Dec 12 20:07:58 raspberrypi bash[1204]: OK
Dec 12 20:07:58 raspberrypi bash[1204]: 24576 is the mpg123 startup volume
Dec 12 20:07:58 raspberrypi bash[1204]: High Performance MPEG 1.0/2.0/2.5 Audio Player for Layers 1, 2 and 3
Dec 12 20:07:58 raspberrypi bash[1204]: #011version 1.25.10; written and copyright by Michael Hipp and others
Dec 12 20:07:58 raspberrypi bash[1204]: #011free software (LGPL) without any warranty but with best wishes
Dec 12 20:07:59 raspberrypi systemd[1]: phoniebox-gpio-control.service: Service RestartSec=3s expired, scheduling restart.
Dec 12 20:07:59 raspberrypi systemd[1]: phoniebox-gpio-control.service: Scheduled restart job, restart counter is at 3.
Dec 12 20:07:59 raspberrypi systemd[1]: Stopped Phoniebox GPIO Control Service.
Dec 12 20:07:59 raspberrypi systemd[1]: Started Phoniebox GPIO Control Service.
Dec 12 20:08:00 raspberrypi bash[1204]: Directory: /home/pi/RPi-Jukebox-RFID/shared/
Dec 12 20:08:00 raspberrypi bash[1204]: Playing MPEG stream 1 of 1: startupsound.mp3 ...
Dec 12 20:08:00 raspberrypi bash[1204]: MPEG 1.0 L III cbr64 44100 j-s
Dec 12 20:08:00 raspberrypi bash[1204]: Artist:  Phoniebox
Dec 12 20:08:01 raspberrypi mpd: exception: Failed to bind to '[::1]:6600'
Dec 12 20:08:01 raspberrypi mpd: exception: nested: Failed to bind socket: Address already in use
Dec 12 20:08:02 raspberrypi systemd[833]: mpd.service: Main process exited, code=exited, status=1/FAILURE
Dec 12 20:08:02 raspberrypi systemd[833]: mpd.service: Failed with result 'exit-code'.
Dec 12 20:08:02 raspberrypi systemd[833]: Failed to start Music Player Daemon.
Dec 12 20:08:02 raspberrypi systemd[833]: Reached target Default.
Dec 12 20:08:02 raspberrypi systemd[833]: Startup finished in 34.077s.
Dec 12 20:08:02 raspberrypi PhonieboxGPIOControl[1321]: INFO:root:['VolumeControl', 'PrevNextControl', 'PlayPause', 'Shutdown', 'Volume0', 'VolumeUp', 'VolumeDown', 'NextSong', 'PrevSong', 'Halt']
Dec 12 20:08:02 raspberrypi PhonieboxGPIOControl[1321]: INFO:root:adding GPIO-Device, VolumeControl
Dec 12 20:08:02 raspberrypi PhonieboxGPIOControl[1321]: INFO:gpio_control:VolumeControl as TwoButtonControl
Dec 12 20:08:02 raspberrypi PhonieboxGPIOControl[1321]: INFO:GPIODevices.two_button_control:adding new action
Dec 12 20:08:02 raspberrypi PhonieboxGPIOControl[1321]: INFO:GPIODevices.simple_button:{}: set when_pressed
Dec 12 20:08:02 raspberrypi PhonieboxGPIOControl[1321]: INFO:GPIODevices.simple_button:add new action
Dec 12 20:08:02 raspberrypi PhonieboxGPIOControl[1321]: INFO:GPIODevices.simple_button:{}: set when_pressed
Dec 12 20:08:02 raspberrypi PhonieboxGPIOControl[1321]: INFO:GPIODevices.simple_button:add new action
Dec 12 20:08:03 raspberrypi PhonieboxGPIOControl[1321]: INFO:root:adding GPIO-Device, PrevNextControl
Dec 12 20:08:03 raspberrypi PhonieboxGPIOControl[1321]: INFO:root:adding TwoButtonControl
Dec 12 20:08:03 raspberrypi PhonieboxGPIOControl[1321]: INFO:GPIODevices.two_button_control:adding new action
Dec 12 20:08:03 raspberrypi PhonieboxGPIOControl[1321]: INFO:GPIODevices.simple_button:{}: set when_pressed
Dec 12 20:08:03 raspberrypi PhonieboxGPIOControl[1321]: INFO:GPIODevices.simple_button:add new action
Dec 12 20:08:04 raspberrypi PhonieboxGPIOControl[1321]: INFO:GPIODevices.simple_button:{}: set when_pressed
Dec 12 20:08:04 raspberrypi PhonieboxGPIOControl[1321]: INFO:GPIODevices.simple_button:add new action
Dec 12 20:08:04 raspberrypi PhonieboxGPIOControl[1321]: INFO:root:adding GPIO-Device, PlayPause
Dec 12 20:08:04 raspberrypi PhonieboxGPIOControl[1321]: INFO:root:Device Shutdown not enabled
Dec 12 20:08:04 raspberrypi PhonieboxGPIOControl[1321]: INFO:root:Device Volume0 not enabled
Dec 12 20:08:04 raspberrypi PhonieboxGPIOControl[1321]: INFO:root:Device VolumeUp not enabled
Dec 12 20:08:04 raspberrypi PhonieboxGPIOControl[1321]: INFO:root:Device VolumeDown not enabled
Dec 12 20:08:04 raspberrypi PhonieboxGPIOControl[1321]: INFO:root:Device NextSong not enabled
Dec 12 20:08:04 raspberrypi PhonieboxGPIOControl[1321]: INFO:root:Device PrevSong not enabled
Dec 12 20:08:04 raspberrypi PhonieboxGPIOControl[1321]: INFO:root:Device Halt not enabled
Dec 12 20:08:04 raspberrypi PhonieboxGPIOControl[1321]: INFO:root:Ready for taking actions
Dec 12 20:08:04 raspberrypi systemd[1]: apt-daily.service: Succeeded.
Dec 12 20:08:05 raspberrypi systemd[1]: Started Daily apt download activities.
Dec 12 20:08:05 raspberrypi bash[1204]: [0:04] Decoding of startupsound.mp3 finished.
Dec 12 20:08:05 raspberrypi systemd[1]: Starting Daily apt upgrade and clean activities...
Dec 12 20:08:05 raspberrypi bash[1204]: Updating DB (#1) ...
Dec 12 20:08:05 raspberrypi bash[1204]: volume: 75%   repeat: off   random: off   single: off   consume: off
Dec 12 20:08:05 raspberrypi mpd: update: updating Thomas auf Schatzsuche/01 Duncans Trick (01. Schmalspurlok).mp3
Dec 12 20:08:05 raspberrypi systemd[1]: Started Phoniebox Startup.
Dec 12 20:08:05 raspberrypi systemd[1]: Reached target Multi-User System.
Dec 12 20:08:05 raspberrypi systemd[1]: Starting Update UTMP about System Runlevel Changes...
Dec 12 20:08:05 raspberrypi systemd[1]: systemd-update-utmp-runlevel.service: Succeeded.
Dec 12 20:08:05 raspberrypi systemd[1]: Started Update UTMP about System Runlevel Changes.
Dec 12 20:08:10 raspberrypi systemd[1]: apt-daily-upgrade.service: Succeeded.
Dec 12 20:08:10 raspberrypi systemd[1]: Started Daily apt upgrade and clean activities.
Dec 12 20:08:10 raspberrypi systemd[1]: Startup finished in 3.982s (kernel) + 1min 29.196s (userspace) = 1min 33.179s.
```

### Base image and version

```
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
```

### Branch / Release

```
Refresh index: 100% (392/392), done.
On branch master
Your branch is up to date with 'origin/master'.
```
### RaspberryPi version

Raspberry Pi Zero W Rev 1.1

### RFID Reader

AZDelivery RFID Kit RC522

### Soundcard

iHaospace Interface I2S PCM5102 DAC Decoder GY-PCM5102 I2S Player Module for Raspberry Pi

![IMG_20201212_202050](https://user-images.githubusercontent.com/2110466/101993069-eabf0100-3cb7-11eb-9712-ace04d40de13.jpg)

**Comment by MrReSc** [comment]
I use different hardware and can't tell you if the info in the wiki is correct, but have you read the page in the wiki about [special reders](https://github.com/MiczFlor/RPi-Jukebox-RFID/wiki/RFID-Reader-Special)? Maybe you can find help there.

**Comment by NicoBleh** [comment]
The reader is the recommended one from the Readme.
https://amzn.to/2C7YZCZ
I had a look at the wiki about special readers and also followed the suggestions but no luck.
What i find interesting is that the provided wiring from the merchant differs from the wiki where the IRQ Pin is not connected.
https://cdn.shopify.com/s/files/1/1509/1638/files/RFID_RC522_Set_mit_Reader_Chip_und_Card_13_56MHz_Raspberry_Pi_Schematic.pdf?8907146477526484569
What now got my attention is when reading the logs:
```
Dec 14 21:28:18 raspberrypi systemd[1]: Stopping Phoniebox RFID-Reader Service...
Dec 14 21:28:18 raspberrypi systemd[1]: phoniebox-rfid-reader.service: Main process exited, code=killed, status=15/TERM
Dec 14 21:28:18 raspberrypi systemd[1]: phoniebox-rfid-reader.service: Succeeded.
Dec 14 21:28:18 raspberrypi systemd[1]: Stopped Phoniebox RFID-Reader Service.
Dec 14 21:28:26 raspberrypi systemd[1]: Started Phoniebox RFID-Reader Service.
Dec 14 21:28:29 raspberrypi daemon_rfid_reader.py[3961]: /usr/local/lib/python3.7/dist-packages/pirc522/rfid.py:90: RuntimeWarning: This channel is already in use, continuing anyway.  Use GPIO.setwarnings(False) to disable warnings.
```

**Comment by seagullki** [comment]
the same with Pi4
[RF1D-RC522 keine Funktion #1204](https://github.com/MiczFlor/RPi-Jukebox-RFID/issues/1204)

**Comment by seagullki** [comment]
with a Kabel from RC522 "IRQ" to PIN 18 (GPIO 24) it works!

**Comment by NicoBleh** [comment]
@seagullki sadly not working with me.

Here is my wiring:

Color | RPi | GPIO | RC522 | Pin
------|---|-------|---------|---- 
red |	17|	Vcc|	Vcc|	    1	
green	|18	|GPIO24|	    IRQ	|    4	
violet	|19	|MOSI	   | MOSI	|6	
yellow	|20|	GND|	        GND	|    3	
blue	|21	|MISO	    |MISO|	5	
orange	|22	|GPIO25	|    RST	|    2	
grey	|23	|SCLK	   | SCK	   | 7	
white|	24	|GPIO8/CE0	|SDA |    8

**Comment by Toqqi** [comment]
@NicoBleh 

Here's my wiring for RC522:

RPi | GPIO | RC522 | Pin
-- | -- | -- | --
**1** | Vcc | Vcc | 1
18 | GPIO24 | IRQ | 4
19 | MOSI | MOSI | 6
**6** | GND | GND | 3
21 | MISO | MISO | 5
22 | GPIO25 | RST | 2
23 | SCLK | SCK | 7
24 | GPIO8/CE0 | SDA | 8

**Comment by NicoBleh** [comment]
@Toqqi ok that is the same except of vcc and ground which I take from rpi pin 17 and 20.
Have you done any special configuration?

**Comment by s-martin** [comment]
Can you try anyway, if @Toqqi's config works for you, too?

**Comment by NicoBleh** [comment]
@s-martin changed to @Toqqi wiring with the same result.

**Comment by Toqqi** [comment]
@NicoBleh Which pins are used by the soundcard?

**Comment by NicoBleh** [comment]
Ok so this is now what i tried.

- I disconnected the soundcard and only have the cardreader connected with @Toqqi 's pinout.
- Erased the SD-card and put Raspberry PI OSLite (32-bit) on it.
- Startup, enter raspi-config and activate spi
- installed `python-dev python-pip git`
- then `pip install spidev` and `pip install pi-rc522`
- `git clone https://github.com/ondryaso/pi-rc522.git`
- reboot
- executed `python /home/pi/pi-rc522/examples/Read.py`

It is showing 'Starting' but when I swipe a card or the keychain there is nothing read.

Not sure if I miss something or the reader is actually broken.
It does have a red led lit.

Any ideas?

**Comment by NicoBleh** [comment]
Update:
After trying back and forth I bought the RFID Reader again, connected it with my initial wiring and it works out of the box.
