### ISSUE TITLE
🐛 | Installation fails on RegisterDevice.py

### ISSUE THREAD

**Issue by bgraeb** [MiczFlor/RPi-Jukebox-RFID#1501]
### What I did

started the one line installer

### What happened

failed here:

```
#
# INSTALLATION FINISHED
#
#####################################################

If you are using an RFID reader, connect it to your RPi.
(In case your RFID reader required soldering, consult the manual.)
Have you connected your RFID reader? [Y/n] y
Please select the RFID reader you want to use
1) USB-Reader (e.g. Neuftech)
2) RC522
3) PN532
4) Manual configuration
5) Multiple RFID reader
#? 1
Choose the reader from list
0 Barcode Reader 
Device Number: 0
Exception ignored in: <function InputDevice.__del__ at 0x760e5b70>
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/evdev/device.py", line 160, in __del__
  File "/usr/local/lib/python3.7/dist-packages/evdev/device.py", line 305, in close
  File "/usr/local/lib/python3.7/dist-packages/evdev/eventio_async.py", line 55, in close
  File "/usr/lib/python3.7/asyncio/events.py", line 640, in get_event_loop
  File "/usr/lib/python3.7/asyncio/events.py", line 660, in new_event_loop
  File "/usr/lib/python3.7/asyncio/unix_events.py", line 51, in __init__
  File "/usr/lib/python3.7/asyncio/selector_events.py", line 49, in __init__
  File "/usr/lib/python3.7/asyncio/base_events.py", line 373, in __init__
  File "/usr/lib/python3.7/asyncio/coroutines.py", line 28, in _is_debug_mode
AttributeError: 'NoneType' object has no attribute 'dev_mode'
Exception ignored in: <function BaseEventLoop.__del__ at 0x761561e0>
Traceback (most recent call last):
  File "/usr/lib/python3.7/asyncio/base_events.py", line 622, in __del__
  File "/usr/lib/python3.7/asyncio/base_events.py", line 390, in __repr__
  File "/usr/lib/python3.7/asyncio/base_events.py", line 1794, in get_debug
AttributeError: '_UnixSelectorEventLoop' object has no attribute '_debug'

DONE. Let the sounds begin.
```

### I expected this to happen

setup of rfid reader should be successful

### Further information that might help

```
-- Logs begin at Thu 2021-09-02 15:20:43 BST, end at Thu 2021-09-02 15:24:14 BST. --
Sep 02 15:20:48 jukebox systemd[1]: Starting Mopidy music server...
Sep 02 15:20:48 jukebox systemd[1]: Started Mopidy music server.
Sep 02 15:20:55 jukebox mopidy[540]: INFO     [MainThread] mopidy.__main__ Starting Mopidy 3.2.0
Sep 02 15:20:55 jukebox mopidy[540]: INFO     [MainThread] mopidy.config Loading config from builtin defaults
Sep 02 15:20:55 jukebox mopidy[540]: INFO     [MainThread] mopidy.config Loading config from file:///usr/share/mopidy/conf.d/mopidy.conf
Sep 02 15:20:55 jukebox mopidy[540]: INFO     [MainThread] mopidy.config Loading config from file:///usr/share/mopidy/conf.d/mopidy-local.conf
Sep 02 15:20:55 jukebox mopidy[540]: INFO     [MainThread] mopidy.config Loading config from file:///etc/mopidy/mopidy.conf
Sep 02 15:20:55 jukebox mopidy[540]: INFO     [MainThread] mopidy.config Loading config from command line options
Sep 02 15:20:55 jukebox mopidy[540]: ERROR    [MainThread] mopidy.internal.log Loading logging config '/etc/mopidy/logging.conf' failed. 'formatters'
Sep 02 15:20:56 jukebox mopidy[540]: INFO     [MainThread] mopidy.__main__ Enabled extensions: spotify, iris, softwaremixer, stream, http, m3u, local, mpd, file
Sep 02 15:20:56 jukebox mopidy[540]: INFO     [MainThread] mopidy.__main__ Disabled extensions: none
Sep 02 15:20:57 jukebox mopidy[540]: INFO     [MainThread] mopidy.commands Starting Mopidy mixer: SoftwareMixer
Sep 02 15:20:57 jukebox mopidy[540]: INFO     [MainThread] mopidy.commands Mixer volume set to 30
Sep 02 15:20:57 jukebox mopidy[540]: INFO     [MainThread] mopidy.commands Starting Mopidy audio
Sep 02 15:20:57 jukebox mopidy[540]: INFO     [MainThread] mopidy.commands Starting Mopidy backends: FileBackend, M3UBackend, StreamBackend, SpotifyBackend, LocalBackend
Sep 02 15:20:57 jukebox mopidy[540]: INFO     [Audio-2] mopidy.audio.actor Audio output set to "alsasink"
Sep 02 15:20:58 jukebox mopidy[540]: INFO     [SpotifyEventLoop] mopidy_spotify.backend Logged in to Spotify in online mode
Sep 02 15:20:58 jukebox mopidy[540]: INFO     [SpotifyBackend-6] mopidy_spotify.web Logged into Spotify Web API as d5l7k1dqq59jr1qrtdlicykiq
Sep 02 15:20:59 jukebox mopidy[540]: INFO     [SpotifyBackend-6] mopidy_spotify.playlists Refreshed 2 Spotify playlists
Sep 02 15:20:59 jukebox mopidy[540]: INFO     [MainThread] mopidy.commands Starting Mopidy core
Sep 02 15:20:59 jukebox mopidy[540]: INFO     [MainThread] mopidy.commands Starting Mopidy frontends: HttpFrontend, IrisFrontend, MpdFrontend
Sep 02 15:20:59 jukebox mopidy[540]: INFO     [HttpFrontend-12] mopidy.http.actor HTTP server running at [::ffff:0.0.0.0]:6680
Sep 02 15:20:59 jukebox mopidy[540]: INFO     [IrisFrontend-13] mopidy_iris.core Starting Iris 3.54.2
Sep 02 15:20:59 jukebox mopidy[540]: INFO     [MainThread] mopidy_mpd.actor MPD server running at [::ffff:0.0.0.0]:6600
Sep 02 15:20:59 jukebox mopidy[540]: INFO     [IrisFrontend-13] mopidy.internal.path Creating dir file:///var/lib/mopidy/iris
Sep 02 15:20:59 jukebox mopidy[540]: INFO     [MainThread] mopidy.commands Starting GLib mainloop
Sep 02 15:20:59 jukebox mopidy[540]: INFO     [MpdSession-15] mopidy_mpd.session New MPD connection from [::ffff:127.0.0.1]:49618
Sep 02 15:20:59 jukebox mopidy[540]: INFO     [MpdSession-16] mopidy_mpd.session New MPD connection from [::ffff:127.0.0.1]:49622
Sep 02 15:20:59 jukebox mopidy[540]: INFO     [MpdSession-17] mopidy_mpd.session New MPD connection from [::ffff:127.0.0.1]:49626
Sep 02 15:20:59 jukebox mopidy[540]: INFO     [MpdSession-18] mopidy_mpd.session New MPD connection from [::ffff:127.0.0.1]:49630
Sep 02 15:20:59 jukebox mopidy[540]: INFO     [MpdSession-19] mopidy_mpd.session New MPD connection from [::ffff:127.0.0.1]:49634
Sep 02 15:20:59 jukebox mopidy[540]: INFO     [MpdSession-20] mopidy_mpd.session New MPD connection from [::ffff:127.0.0.1]:49638
Sep 02 15:20:59 jukebox mopidy[540]: INFO     [MpdSession-21] mopidy_mpd.session New MPD connection from [::ffff:127.0.0.1]:49642
Sep 02 15:20:59 jukebox mopidy[540]: INFO     [MpdSession-22] mopidy_mpd.session New MPD connection from [::ffff:127.0.0.1]:49646
Sep 02 15:21:00 jukebox mopidy[540]: INFO     [MpdSession-23] mopidy_mpd.session New MPD connection from [::ffff:127.0.0.1]:49650
Sep 02 15:23:29 jukebox mopidy[540]: INFO     [MpdSession-24] mopidy_mpd.session New MPD connection from [::ffff:127.0.0.1]:49658
Sep 02 15:23:33 jukebox mopidy[540]: INFO     [MpdSession-25] mopidy_mpd.session New MPD connection from [::ffff:127.0.0.1]:49662
```

### Base image and version

```
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
```

### Branch / Release

`master`

### Installscript

`scripts/installscripts/buster-install-default.sh`

### RaspberryPi version

`3 B+`

### RFID Reader

```
Bus 001 Device 004: ID 13ba:0018 PCPlay Barcode PCP-BCG4209
Device Descriptor:
  bLength                18
  bDescriptorType         1
  bcdUSB               1.10
  bDeviceClass            0 
  bDeviceSubClass         0 
  bDeviceProtocol         0 
  bMaxPacketSize0         8
  idVendor           0x13ba PCPlay
  idProduct          0x0018 Barcode PCP-BCG4209
  bcdDevice            0.01
  iManufacturer           0 
  iProduct                1 Barcode Reader 
  iSerial                 0 
  bNumConfigurations      1
  Configuration Descriptor:
    bLength                 9
    bDescriptorType         2
    wTotalLength       0x0022
    bNumInterfaces          1
    bConfigurationValue     1
    iConfiguration          0 
    bmAttributes         0xa0
      (Bus Powered)
      Remote Wakeup
    MaxPower              400mA
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        0
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      1 Boot Interface Subclass
      bInterfaceProtocol      1 Keyboard
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.10
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength      62
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x81  EP 1 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0008  1x 8 bytes
        bInterval               2
can't get debug descriptor: Resource temporarily unavailable
Device Status:     0x0000
  (Bus Powered)
```

### Soundcard

none

### Other notable hardware

none

**Comment by s-martin** [comment]
It looks like you are trying to use a barcode scanner. Currently this is not supported by Phoniebox, but there’s a discussion #562. Please have a look there.

Phoniebox supports different RFID Card readers, see https://github.com/MiczFlor/RPi-Jukebox-RFID#rfid-reader-and-cards--fobs

**Comment by bgraeb** [comment]
it actually is a RFID-Scanner that used to work for 2+ Years with this project but stopped some months ago. I dont know, why it shows "barcode scanner".

When I connect the device to my fedora workstation, I see the RFID-Tags IDs in terminal. So the device seems to work as expected.

**Comment by s-martin** [comment]
Which rfid reader are you using? Do you use PN532? Then please have a look at https://github.com/MiczFlor/RPi-Jukebox-RFID/tree/develop/components/rfid-reader/PN532


Additionally this [thread](https://forums.pimoroni.com/t/problems-running-keyboard-py-with-button-shim/13826/2) (although not directly your problem) suggests that I2C may not be enabled.

**Comment by MiczFlor** [comment]
I have the exact same issue (see below) with the USB RFID reade: 3 Sycreader RFID Technology Co., Ltd SYC ID&IC USB Reader

it's the reader that's linked from the README file.

After reboot, also the webserver does not work

~~~
# INSTALLATION FINISHED
#
#####################################################

If you are using an RFID reader, connect it to your RPi.
(In case your RFID reader required soldering, consult the manual.)
Have you connected your RFID reader? [Y/n] 
Please select the RFID reader you want to use
1) USB-Reader (e.g. Neuftech)  4) Manual configuration
2) RC522		       5) Multiple RFID reader
3) PN532
#? 1
Choose the reader from list
0 Chicony USB Keyboard Consumer Control
1 Chicony USB Keyboard System Control
2 Chicony USB Keyboard
3 Sycreader RFID Technology Co., Ltd SYC ID&IC USB Reader
4 Logitech USB Mouse
Device Number: 3
Exception ignored in: <function InputDevice.__del__ at 0x76190978>
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/evdev/device.py", line 160, in __del__
  File "/usr/local/lib/python3.7/dist-packages/evdev/device.py", line 305, in close
  File "/usr/local/lib/python3.7/dist-packages/evdev/eventio_async.py", line 55, in close
  File "/usr/lib/python3.7/asyncio/events.py", line 640, in get_event_loop
  File "/usr/lib/python3.7/asyncio/events.py", line 660, in new_event_loop
  File "/usr/lib/python3.7/asyncio/unix_events.py", line 51, in __init__
  File "/usr/lib/python3.7/asyncio/selector_events.py", line 49, in __init__
  File "/usr/lib/python3.7/asyncio/base_events.py", line 373, in __init__
  File "/usr/lib/python3.7/asyncio/coroutines.py", line 28, in _is_debug_mode
AttributeError: 'NoneType' object has no attribute 'dev_mode'
Exception ignored in: <function BaseEventLoop.__del__ at 0x761edfa8>
Traceback (most recent call last):
  File "/usr/lib/python3.7/asyncio/base_events.py", line 622, in __del__
  File "/usr/lib/python3.7/asyncio/base_events.py", line 390, in __repr__
  File "/usr/lib/python3.7/asyncio/base_events.py", line 1794, in get_debug
AttributeError: '_UnixSelectorEventLoop' object has no attribute '_debug'
Exception ignored in: <function InputDevice.__del__ at 0x76190978>
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/evdev/device.py", line 160, in __del__
  File "/usr/local/lib/python3.7/dist-packages/evdev/device.py", line 305, in close
  File "/usr/local/lib/python3.7/dist-packages/evdev/eventio_async.py", line 55, in close
  File "/usr/lib/python3.7/asyncio/events.py", line 640, in get_event_loop
  File "/usr/lib/python3.7/asyncio/events.py", line 660, in new_event_loop
  File "/usr/lib/python3.7/asyncio/unix_events.py", line 51, in __init__
  File "/usr/lib/python3.7/asyncio/selector_events.py", line 49, in __init__
  File "/usr/lib/python3.7/asyncio/base_events.py", line 373, in __init__
  File "/usr/lib/python3.7/asyncio/coroutines.py", line 28, in _is_debug_mode
AttributeError: 'NoneType' object has no attribute 'dev_mode'
Exception ignored in: <function BaseEventLoop.__del__ at 0x761edfa8>
Traceback (most recent call last):
  File "/usr/lib/python3.7/asyncio/base_events.py", line 622, in __del__
  File "/usr/lib/python3.7/asyncio/base_events.py", line 390, in __repr__
  File "/usr/lib/python3.7/asyncio/base_events.py", line 1794, in get_debug
AttributeError: '_UnixSelectorEventLoop' object has no attribute '_debug'
Exception ignored in: <function InputDevice.__del__ at 0x76190978>
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/evdev/device.py", line 160, in __del__
  File "/usr/local/lib/python3.7/dist-packages/evdev/device.py", line 305, in close
  File "/usr/local/lib/python3.7/dist-packages/evdev/eventio_async.py", line 55, in close
  File "/usr/lib/python3.7/asyncio/events.py", line 640, in get_event_loop
  File "/usr/lib/python3.7/asyncio/events.py", line 660, in new_event_loop
  File "/usr/lib/python3.7/asyncio/unix_events.py", line 51, in __init__
  File "/usr/lib/python3.7/asyncio/selector_events.py", line 49, in __init__
  File "/usr/lib/python3.7/asyncio/base_events.py", line 373, in __init__
  File "/usr/lib/python3.7/asyncio/coroutines.py", line 28, in _is_debug_mode
AttributeError: 'NoneType' object has no attribute 'dev_mode'
Exception ignored in: <function BaseEventLoop.__del__ at 0x761edfa8>
Traceback (most recent call last):
  File "/usr/lib/python3.7/asyncio/base_events.py", line 622, in __del__
  File "/usr/lib/python3.7/asyncio/base_events.py", line 390, in __repr__
  File "/usr/lib/python3.7/asyncio/base_events.py", line 1794, in get_debug
AttributeError: '_UnixSelectorEventLoop' object has no attribute '_debug'
Exception ignored in: <function InputDevice.__del__ at 0x76190978>
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/evdev/device.py", line 160, in __del__
  File "/usr/local/lib/python3.7/dist-packages/evdev/device.py", line 305, in close
  File "/usr/local/lib/python3.7/dist-packages/evdev/eventio_async.py", line 55, in close
  File "/usr/lib/python3.7/asyncio/events.py", line 640, in get_event_loop
  File "/usr/lib/python3.7/asyncio/events.py", line 660, in new_event_loop
  File "/usr/lib/python3.7/asyncio/unix_events.py", line 51, in __init__
  File "/usr/lib/python3.7/asyncio/selector_events.py", line 49, in __init__
  File "/usr/lib/python3.7/asyncio/base_events.py", line 373, in __init__
  File "/usr/lib/python3.7/asyncio/coroutines.py", line 28, in _is_debug_mode
AttributeError: 'NoneType' object has no attribute 'dev_mode'
Exception ignored in: <function BaseEventLoop.__del__ at 0x761edfa8>
Traceback (most recent call last):
  File "/usr/lib/python3.7/asyncio/base_events.py", line 622, in __del__
  File "/usr/lib/python3.7/asyncio/base_events.py", line 390, in __repr__
  File "/usr/lib/python3.7/asyncio/base_events.py", line 1794, in get_debug
AttributeError: '_UnixSelectorEventLoop' object has no attribute '_debug'
Exception ignored in: <function InputDevice.__del__ at 0x76190978>
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/evdev/device.py", line 160, in __del__
  File "/usr/local/lib/python3.7/dist-packages/evdev/device.py", line 305, in close
  File "/usr/local/lib/python3.7/dist-packages/evdev/eventio_async.py", line 55, in close
  File "/usr/lib/python3.7/asyncio/events.py", line 640, in get_event_loop
  File "/usr/lib/python3.7/asyncio/events.py", line 660, in new_event_loop
  File "/usr/lib/python3.7/asyncio/unix_events.py", line 51, in __init__
  File "/usr/lib/python3.7/asyncio/selector_events.py", line 49, in __init__
  File "/usr/lib/python3.7/asyncio/base_events.py", line 373, in __init__
  File "/usr/lib/python3.7/asyncio/coroutines.py", line 28, in _is_debug_mode
AttributeError: 'NoneType' object has no attribute 'dev_mode'
Exception ignored in: <function BaseEventLoop.__del__ at 0x761edfa8>
Traceback (most recent call last):
  File "/usr/lib/python3.7/asyncio/base_events.py", line 622, in __del__
  File "/usr/lib/python3.7/asyncio/base_events.py", line 390, in __repr__
  File "/usr/lib/python3.7/asyncio/base_events.py", line 1794, in get_debug
AttributeError: '_UnixSelectorEventLoop' object has no attribute '_debug'

DONE. Let the sounds begin.
~~~

**Comment by s-martin** [comment]
Ok, so it’s not related to a specific reader and was probably introduced by the changes of 2.3 release.

**Comment by bgraeb** [comment]
I think I bought the neuftech RFID-Reader. I removed the plastic housing to place the PCB on the topside of my case, so I cant say what there was printed on. The PCB is labeld `M301-V3.1 JATSECURITY`.

**Comment by MiczFlor** [comment]
@s-martin it might have to do with the apt-get default repo list of raspberry ip OS, I have to check again. didn't find the time. I changed the resources list and the install process actually worked, webserver up and all. Also, the RFID ID of a swiped card showed up in the web App interface - so it seems to work.
BUT: the errors that I copied above remained, so the reader seems to work, but the python still has issues.
@bgraeb does the web app work on your installation? 
If not, we might have two issues wrapped in one:

a) Pi OS [resources list does not work over wifi](https://www.raspberrypi.org/forums/viewtopic.php?p=137159&sid=0393ba7cc3dcbc1560ec32edd4c8c624#p137159)
b) the python script of phoniebox for readers works but throws errors...

**Comment by bgraeb** [comment]
@MiczFlor for me stock Raspi OS works without modifications, webinterface works flawless including playing spotify.

Only the RFID-Cards are not read out/used correctly.

**Comment by bgraeb** [comment]
Any updates or thoughts here? Is it more of an implementation issue with standard libs? Maybe I can help out a little, if you can point me in a direction.

**Comment by jardleex** [comment]
Hello,

I'm facing the issue too and did some testing on it.

### Further information that might help
I began building my box on 18th of September. Since then I ran `apt upgrade` 4 times. 
I have two assumptions what may broke it.

**A:** A package update via `apt upgrade`. I ran this command 4 times since I initally instelled the box. In the beginning the reader worked fine. If requested I can provide a list of packages which have been updated on my system since then from `/var/log/apt/history.log`.
**B:** I ran some basic setup things via Ansible on my system (user setup, package installtion, network and localization related stuff). Last changed thing was disabling the user `pi`. I disabled his password and set his login shell to `/sbin/nologin`. Reverting this ain't changed the behaviour but maybe I missed something else.

Executing `python3 /home/pi/RPi-Jukebox-RFID/scripts/daemon_rfid_reader.py` from `/etc/systemd/system/phoniebox-rfid-reader.service` as user `root` works, as `pi` not.

```bash
# user pi
pi@phoniebox1:~ $ id
uid=1000(pi) gid=1000(pi) groups=1000(pi),997(gpio)
pi@phoniebox1:~ $ python3 /home/pi/RPi-Jukebox-RFID/scripts/daemon_rfid_reader.py
Could not find the device HID 16c0:27db Keyboard
. Make sure is connected
pi@phoniebox1:~ $ lsusb | grep 16c0:27db
Bus 001 Device 004: ID 16c0:27db Van Ooijen Technische Informatica Keyboard

# user root - Traceback caused by pressing CTRL+C to end process
root@phoniebox1:/home/pi/RPi-Jukebox-RFID# id
uid=0(root) gid=0(root) groups=0(root),112(bluetooth)
root@phoniebox1:/home/pi/RPi-Jukebox-RFID# python3 /home/pi/RPi-Jukebox-RFID/scripts/daemon_rfid_reader.py
2021-11-26 11:24:19,616 - root - INFO - Dir_PATH: /home/pi/RPi-Jukebox-RFID/scripts
^CTraceback (most recent call last):
  File "/home/pi/RPi-Jukebox-RFID/scripts/daemon_rfid_reader.py", line 95, in <module>
    cardid = reader.reader.readCard()
  File "/home/pi/RPi-Jukebox-RFID/scripts/Reader.py", line 57, in readCard
    r, w, x = select([self.dev], [], [])
KeyboardInterrupt
Exception ignored in: <function InputDevice.__del__ at 0xb612dc90>
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/evdev/device.py", line 160, in __del__
  File "/usr/local/lib/python3.7/dist-packages/evdev/device.py", line 305, in close
  File "/usr/local/lib/python3.7/dist-packages/evdev/eventio_async.py", line 55, in close
  File "/usr/lib/python3.7/asyncio/events.py", line 726, in get_event_loop_policy
  File "/usr/lib/python3.7/asyncio/events.py", line 719, in _init_event_loop_policy
ImportError: sys.meta_path is None, Python is likely shutting down
root@phoniebox1:/home/pi/RPi-Jukebox-RFID#
```

Bypass for me:
When running `phoniebox-rfid-reader.service` as root (disable the user/group lines in ) then the service starts and the reader works.

I do not want to run the box like this, it's just a nasty bypass.

## Software

### Base image and version



### Branch / Release

On branch master
Your branch is up to date with 'origin/master'.

Version2.3 - 2425890 - master
EditionClassic edition (barebones)


### Installscript

`scripts/installscripts/buster-install-default.sh`


## Hardware

### RaspberryPi version

`Raspberry Pi Model B Plus Rev 1.2`

### RFID Reader

```
Neuftech USB RFID Reader ID Kartenlesegerät from Amazon

Bus 001 Device 004: ID 16c0:27db Van Ooijen Technische Informatica Keyboard
Device Descriptor:
  bLength                18
  bDescriptorType         1
  bcdUSB               1.10
  bDeviceClass            0 
  bDeviceSubClass         0 
  bDeviceProtocol         0 
  bMaxPacketSize0         8
  idVendor           0x16c0 Van Ooijen Technische Informatica
  idProduct          0x27db Keyboard
  bcdDevice            0.01
  iManufacturer           1 (error)
  iProduct                0 
  iSerial                 0 
  bNumConfigurations      1
  Configuration Descriptor:
    bLength                 9
    bDescriptorType         2
    wTotalLength       0x0029
    bNumInterfaces          1
    bConfigurationValue     1
    iConfiguration          0 
    bmAttributes         0xa0
      (Bus Powered)
      Remote Wakeup
    MaxPower              500mA
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        0
      bAlternateSetting       0
      bNumEndpoints           2
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      0 
      bInterfaceProtocol      0 
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.10
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength      61
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x81  EP 1 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0008  1x 8 bytes
        bInterval              10
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x01  EP 1 OUT
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0008  1x 8 bytes
        bInterval              10
Device Status:     0x0000
  (Bus Powered)
```

### Soundcard

`Onboard + HifiBerry MiniAmp`

### Other notable hardware

`none`
