### ISSUE TITLE
run_configure_rfid_reader: Wrong keyword for card removal action

### ISSUE THREAD

**Issue by ChisSoc** [MiczFlor/RPi-Jukebox-RFID#1695]
### Discussed in https://github.com/MiczFlor/RPi-Jukebox-RFID/discussions/1694

<div type='discussions-op-text'>

<sup>Originally posted by **jeverling** December 31, 2021</sup>
Hi all, I'm trying to use the `place_not_swipe` option. 

In `rfid.yaml`:
```
      place_not_swipe:
        enabled: true
        card_removal_action:
          quick_select: pause
```

It seems, that you have to use `alias` instead of `quick_select` now, right? https://github.com/MiczFlor/RPi-Jukebox-RFID/pull/1584/files

If I just try `alias: pause`, I get an error:

```
Exception in thread read_00CRemover:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/home/pi/RPi-Jukebox-RFID/src/jukebox/components/rfid/reader/__init__.py", line 48, in run
    self.timeout_action()
TypeError: call_ignore_errors() got an unexpected keyword argument 'note'
```

Any idea how I have to set this option so it works, and pause is triggered when removing the card?</div>

You're right. The config file entry must look like this:

      place_not_swipe:
        enabled: true
        card_removal_action:
          alias: pause
Well spotted! That is a bug in the config script.

**Comment by ChisSoc** [comment]
Fixed in [Release 3.1.1](https://github.com/MiczFlor/RPi-Jukebox-RFID/releases/tag/V3.1.1)
