### ISSUE TITLE
Try to work with special RFID Reader (GIS TS-R38)

### ISSUE THREAD

**Issue by Gambit359** [MiczFlor/RPi-Jukebox-RFID#1731]
Hi,
first I want to thank MiczFlor for this great work.

I would like to build a Phoniebox for my son and the goal is to use mostly stuff I already got under my desk. So I have an [GIS TS-R38 RFID Reader](https://www.gis-net.de/rfid/english/125khz/ts_rw38.htm). I#m able to setup this thing like I want. So It is in HID Mode and it sends an 10 characters Hex-number and an ENTER (CR). I can see this in the raspberry Terminal.

`lsusb` says: `Bus 001 Device 007: ID 1c40:05ab EZPrototypes`

`ls -la /dev/input/by-id/lrwxrwxrwx` says: `1 root root   9 Jan 14 19:45 usb-GiS_mbH_TS-RW38_HID_1650-5867-event-kbd -> ../event3`

with `python3 RegisterDevice.py ` there is `0 GiS mbH TS-RW38 HID`. But if I choose 0 I got an Error Message:
```
Exception ignored in: <function InputDevice.__del__ at 0x761b2fa8>
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/evdev/device.py", line 160, in __del__
  File "/usr/local/lib/python3.7/dist-packages/evdev/device.py", line 305, in close
  File "/usr/local/lib/python3.7/dist-packages/evdev/eventio_async.py", line 55, in close
  File "/usr/lib/python3.7/asyncio/events.py", line 640, in get_event_loop
  File "/usr/lib/python3.7/asyncio/events.py", line 660, in new_event_loop
  File "/usr/lib/python3.7/asyncio/unix_events.py", line 51, in __init__
  File "/usr/lib/python3.7/asyncio/selector_events.py", line 49, in __init__
  File "/usr/lib/python3.7/asyncio/base_events.py", line 373, in __init__
  File "/usr/lib/python3.7/asyncio/coroutines.py", line 28, in _is_debug_mode
AttributeError: 'NoneType' object has no attribute 'dev_mode'
Exception ignored in: <function BaseEventLoop.__del__ at 0x761f3618> 
```
an so on ...

After that I got GiS mbH TS-RW38 HID in deviceName.txt but no changes in latestID.txt when I use an RFID-Chip.

Is there anything I can do to make this Reader work?

Thanks a lot!

**Comment by Gambit359** [comment]
It works. I have no idea why. Tried it the last 3 days and 10 minutes after this post it works!
