### ISSUE TITLE
[Bugfix] Webapp does not all to assign single song to card

### ISSUE THREAD

**Issue by pabera** [MiczFlor/RPi-Jukebox-RFID#2141]
When assigning a single song to a card in folder view, an error occurs. 

```
ERROR
Cannot destructure property 'artist' of 'song' as it is undefined.
TypeError: Cannot destructure property 'artist' of 'song' as it is undefined.
    at SongListItem (http://localhost:3000/static/js/bundle.js:5143:5)
    at renderWithHooks (http://localhost:3000/static/js/bundle.js:94021:22)
    at updateFunctionComponent (http://localhost:3000/static/js/bundle.js:96123:24)
    at updateSimpleMemoComponent (http://localhost:3000/static/js/bundle.js:96002:14)
    at beginWork (http://localhost:3000/static/js/bundle.js:97627:20)
    at HTMLUnknownElement.callCallback (http://localhost:3000/static/js/bundle.js:84596:18)
    at Object.invokeGuardedCallbackDev (http://localhost:3000/static/js/bundle.js:84640:20)
    at invokeGuardedCallback (http://localhost:3000/static/js/bundle.js:84695:35)
    at beginWork$1 (http://localhost:3000/static/js/bundle.js:101691:11)
    at performUnitOfWork (http://localhost:3000/static/js/bundle.js:100702:16)
```

**Comment by pabera** [comment]
https://github.com/MiczFlor/RPi-Jukebox-RFID/pull/2143
